# This is a basic workflow to help you get started with Actions

name: Youtube Stats Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    #strategy:
    #  matrix:
    #    node-version: [12.x. 14.x, 16.x]
        #See supported Node.js release schedule at https://node.js/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        run: actions/setup-node@v3 #installation of node env
          
      - run : npm install # dependencies installation
      - run : npm run build --if-present # build development project
